# Generated by Django 5.2.17 on 2026-09-19 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive entries are hidden from new forms.",
                        verbose_name="active",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="sort order")),
                (
                    "show_on_jobs",
                    models.BooleanField(
                        default=False,
                        help_text="Show a dropdown for this type on every job day.",
                        verbose_name="pick on jobs",
                    ),
                ),
                (
                    "allow_multiple",
                    models.BooleanField(
                        default=False,
                        help_text="Allow picking more than one per day (e.g. batteries).",
                        verbose_name="several per day",
                    ),
                ),
            ],
            options={
                "verbose_name": "equipment type",
                "verbose_name_plural": "equipment types",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True, verbose_name="deleted"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. “T50 #1”", max_length=100, verbose_name="name"
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100, verbose_name="model")),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Used to match imported flight records to this item.",
                        max_length=100,
                        verbose_name="serial number",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(blank=True, null=True, verbose_name="bought on"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "In use"),
                            ("spare", "Spare"),
                            ("retired", "Retired"),
                            ("sold", "Sold"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "equipment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="equipment.equipmenttype",
                        verbose_name="type",
                    ),
                ),
            ],
            options={
                "verbose_name": "equipment",
                "verbose_name_plural": "equipment",
                "ordering": ["equipment_type__sort_order", "equipment_type__name", "name"],
            },
        ),
    ]
