# Generated by Django 5.2.17 on 2026-09-19 18:04

import avifly.imports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0002_default_lists"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("importer_key", models.CharField(max_length=50, verbose_name="importer")),
                ("original_name", models.CharField(max_length=255, verbose_name="file")),
                ("file", models.FileField(upload_to=avifly.imports.models.import_path)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "import",
                "verbose_name_plural": "imports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=200)),
                ("date", models.DateField(verbose_name="date")),
                ("start_time", models.TimeField(blank=True, null=True, verbose_name="start")),
                ("end_time", models.TimeField(blank=True, null=True, verbose_name="end")),
                (
                    "hectares",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="hectares",
                    ),
                ),
                (
                    "equipment_serial",
                    models.CharField(blank=True, max_length=100, verbose_name="serial number"),
                ),
                ("raw", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("duplicate", "Already imported"),
                            ("applied", "Added to a job"),
                            ("skipped", "Skipped"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="imports.importbatch",
                    ),
                ),
                (
                    "job_day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="jobs.jobday",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time", "pk"],
            },
        ),
    ]
