# Generated by Django 5.2.17 on 2026-09-19 17:48

import avifly.jobs.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("equipment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive entries are hidden from new forms.",
                        verbose_name="active",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="sort order")),
            ],
            options={
                "verbose_name": "crop",
                "verbose_name_plural": "crops",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OperationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive entries are hidden from new forms.",
                        verbose_name="active",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="sort order")),
                (
                    "default_rate_per_ha",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="default rate per ha",
                    ),
                ),
            ],
            options={
                "verbose_name": "operation type",
                "verbose_name_plural": "operation types",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True, verbose_name="deleted"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(editable=False)),
                ("sequence", models.PositiveIntegerField(editable=False)),
                (
                    "number",
                    models.CharField(
                        editable=False, max_length=20, unique=True, verbose_name="job number"
                    ),
                ),
                (
                    "material_note",
                    models.CharField(
                        blank=True,
                        help_text="What was sprayed or spread (supplied by the customer).",
                        max_length=500,
                        verbose_name="material",
                    ),
                ),
                (
                    "rate_per_ha",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="rate per ha",
                    ),
                ),
                ("is_multi_day", models.BooleanField(default=False, verbose_name="multi-day job")),
                ("is_cancelled", models.BooleanField(default=False, verbose_name="cancelled")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="planned",
                        editable=False,
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_index=True, editable=False, null=True, verbose_name="first day"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        db_index=True, editable=False, null=True, verbose_name="last day"
                    ),
                ),
                (
                    "total_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=10,
                        verbose_name="hectares",
                    ),
                ),
                (
                    "work_minutes",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="work time (min)"
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="hectares × rate",
                    ),
                ),
                (
                    "extras_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="extra charges",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="total",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="jobs.crop",
                        verbose_name="crop",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="customers.customer",
                        verbose_name="customer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "operation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="jobs.operationtype",
                        verbose_name="operation",
                    ),
                ),
            ],
            options={
                "verbose_name": "job",
                "verbose_name_plural": "jobs",
                "ordering": ["-start_date", "-year", "-sequence"],
                "permissions": [
                    ("view_all_jobs", "Can view everyone's jobs"),
                    ("change_all_jobs", "Can edit everyone's jobs"),
                    ("delete_all_jobs", "Can delete everyone's jobs"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExtraCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("note", models.CharField(max_length=200, verbose_name="what for")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="amount"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_charges",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "extra charge",
                "verbose_name_plural": "extra charges",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="JobPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                (
                    "image",
                    models.ImageField(
                        upload_to=avifly.jobs.models.job_photo_path, verbose_name="photo"
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200, verbose_name="caption")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "job photo",
                "verbose_name_plural": "job photos",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=1, verbose_name="day")),
                ("date", models.DateField(verbose_name="date")),
                ("start_time", models.TimeField(blank=True, null=True, verbose_name="start")),
                ("end_time", models.TimeField(blank=True, null=True, verbose_name="end")),
                (
                    "hectares",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="hectares",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=300, verbose_name="notes")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "source",
                    models.CharField(
                        default="manual", editable=False, max_length=50, verbose_name="source"
                    ),
                ),
                ("external_id", models.CharField(blank=True, editable=False, max_length=200)),
                ("raw_data", models.JSONField(blank=True, editable=False, null=True)),
                (
                    "crew",
                    models.ManyToManyField(
                        blank=True,
                        related_name="job_days",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="crew",
                    ),
                ),
                (
                    "equipment",
                    models.ManyToManyField(
                        blank=True,
                        related_name="job_days",
                        to="equipment.equipment",
                        verbose_name="equipment",
                    ),
                ),
                (
                    "farm_fields",
                    models.ManyToManyField(
                        blank=True,
                        related_name="job_days",
                        to="customers.farmfield",
                        verbose_name="fields",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "job day",
                "verbose_name_plural": "job days",
                "ordering": ["position", "date", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_id", ""), _negated=True),
                        fields=("source", "external_id"),
                        name="jobday_unique_external_record",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("year", "sequence"), name="job_unique_year_sequence"
            ),
        ),
    ]
