# Generated by Django 5.2.17 on 2026-09-19 17:52

import avifly.money.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("equipment", "0002_default_types"),
        ("jobs", "0002_default_lists"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive entries are hidden from new forms.",
                        verbose_name="active",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="sort order")),
            ],
            options={
                "verbose_name": "cost category",
                "verbose_name_plural": "cost categories",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MoneyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive entries are hidden from new forms.",
                        verbose_name="active",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="sort order")),
            ],
            options={
                "verbose_name": "money account",
                "verbose_name_plural": "money accounts",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive entries are hidden from new forms.",
                        verbose_name="active",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="sort order")),
            ],
            options={
                "verbose_name": "payment method",
                "verbose_name_plural": "payment methods",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True, verbose_name="deleted"
                    ),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="date"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="amount",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="e.g. “New propeller” or “Diesel”",
                        max_length=200,
                        verbose_name="what for",
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        upload_to=avifly.money.models.receipt_path,
                        verbose_name="receipt",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costs",
                        to="equipment.equipment",
                        verbose_name="equipment",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costs",
                        to="jobs.job",
                        verbose_name="job",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="costs",
                        to="money.costcategory",
                        verbose_name="category",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        default=avifly.money.models.default_account_id,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="costs",
                        to="money.moneyaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "cost",
                "verbose_name_plural": "costs",
                "ordering": ["-date", "-pk"],
                "permissions": [
                    ("view_all_costs", "Can view everyone's costs"),
                    ("change_all_costs", "Can edit everyone's costs"),
                    ("delete_all_costs", "Can delete everyone's costs"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True, verbose_name="deleted"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="amount"),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="date"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="e.g. invoice number",
                        max_length=300,
                        verbose_name="note",
                    ),
                ),
                (
                    "follows_job_total",
                    models.BooleanField(
                        default=True,
                        help_text="Keeps the amount equal to the job total, even when the job changes.",
                        verbose_name="same as job total",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "Paid")],
                        default="paid",
                        editable=False,
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        default=avifly.money.models.default_account_id,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="money.moneyaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="jobs.job",
                        verbose_name="job",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="money.paymentmethod",
                        verbose_name="method",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-date", "-pk"],
            },
        ),
    ]
