# Generated by Django 5.2.17 on 2026-09-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Avifly", max_length=200, verbose_name="business name"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MKD",
                        help_text="Shown after amounts, e.g. MKD.",
                        max_length=10,
                        verbose_name="currency",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=300, verbose_name="address")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="phone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email")),
                (
                    "tax_number",
                    models.CharField(blank=True, max_length=50, verbose_name="tax number"),
                ),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=100, verbose_name="bank account"),
                ),
            ],
            options={
                "verbose_name": "business settings",
                "verbose_name_plural": "business settings",
                "permissions": [
                    ("manage_settings", "Can edit business settings and lists"),
                    ("view_history", "Can view change history"),
                    ("use_bin", "Can restore deleted items"),
                ],
            },
        ),
    ]
