# Generated by Django 5.2.17 on 2026-09-19 17:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True, verbose_name="deleted"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, verbose_name="company"),
                ),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="phone")),
                (
                    "phone_alt",
                    models.CharField(blank=True, max_length=50, verbose_name="other phone"),
                ),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="e-mail")),
                (
                    "town",
                    models.CharField(blank=True, max_length=100, verbose_name="town / village"),
                ),
                ("address", models.CharField(blank=True, max_length=300, verbose_name="address")),
                (
                    "tax_number",
                    models.CharField(blank=True, max_length=50, verbose_name="tax number"),
                ),
                (
                    "special_rate_per_ha",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave empty to use the normal rate for the operation.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="special rate per ha",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive customers are hidden from new jobs.",
                        verbose_name="active",
                    ),
                ),
                ("search_text", models.TextField(blank=True, editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
            ],
            options={
                "verbose_name": "customer",
                "verbose_name_plural": "customers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FarmField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True, verbose_name="deleted"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "hectares",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="size (ha)",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="longitude",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Obstacles, power lines, beehives, access…",
                        verbose_name="notes",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="farm_fields",
                        to="customers.customer",
                        verbose_name="customer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
            ],
            options={
                "verbose_name": "field",
                "verbose_name_plural": "fields",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__isnull", True),
                            models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                            _connector="OR",
                        ),
                        name="farmfield_latitude_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longitude__isnull", True),
                            models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                            _connector="OR",
                        ),
                        name="farmfield_longitude_range",
                    ),
                ],
            },
        ),
    ]
